version: '3.7'

services:
  glpi:
    image: glpi/glpi:11.0.2
    container_name: glpi_app
    restart: always
    ports:
      - "8200:80"
    depends_on:
      - db
    environment:
      - TZ=America/Bogota
      - GLPI_DB_HOST=db
      - GLPI_DB_USER=glpi
      - GLPI_DB_PASSWORD=glpi
      - GLPI_DB_NAME=glpi
    volumes:
      - as_tooli_ia_glpi_data:/var/www/html/glpi
      - as_tooli_ia_glpi_files:/var/www/html/files
      - as_tooli_ia_glpi_plugins:/var/www/html/plugins
      - as_tooli_ia_glpi_marketplace:/var/www/html/marketplace

  db:
    image: mariadb:10.11
    container_name: glpi_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    volumes:
      - as_tooli_ia_db_data:/var/lib/mysql

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_app
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Bogota
      - N8N_SECURE_COOKIE=false
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=1234
    volumes:
      - as_tooli_ia_n8n_data:/home/node/.n8n

volumes:
  as_tooli_ia_db_data:
    external: true
  as_tooli_ia_glpi_data:
    external: true
  as_tooli_ia_glpi_files:           # NUEVO
  as_tooli_ia_glpi_plugins:         # NUEVO
  as_tooli_ia_glpi_marketplace:     # NUEVO
  as_tooli_ia_n8n_data:
    external: true